POST http://localhost:3010/api/insertUser
Content-Type: application/json

{
    "email": "johneymdan.doe@example.com",
    "name": "John Doe",
    "password": "securepassword123",
    "role": 2,
    "keywords": []
}
